import localFont from "next/font/local";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Navbar from "./components/Navbar";
import "./globals.css";

const satoshi = localFont({
  src: "./fonts/Satoshi-Regular.woff",
  variable: "--font-satoshi",

  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable}  antialiased`}>
        <div className="flex h-screen mx-auto bg-white max-h-screen">
          <div className="w-64 bg-gray-900 text-white flex flex-col">
            <Header />
            <Navbar />
            <Footer />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
